FROM python:3.13.14-slim

WORKDIR /app

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"
ENV UV_COMPILE_BYTECODE=1
ENV PYTHONPATH="/app/src"

COPY pyproject.toml .
COPY uv.lock .

RUN pip install --no-cache-dir uv==0.11.32
RUN uv sync --frozen --no-install-project --no-dev

COPY src/agents/ ./src/agents/
COPY src/business/ ./src/business/
COPY src/core/ ./src/core/
COPY src/mcp_servers/ ./src/mcp_servers/
COPY src/memory/ ./src/memory/
COPY src/schema/ ./src/schema/
COPY src/service/ ./src/service/
COPY src/run_service.py ./src/run_service.py

CMD ["python", "src/run_service.py"]